angular.module('introGame.app', ['ngAudio',
                                'introGame.routing',
                                'introGame.albumController',
                                'introGame.songController',
                                'introGame.answerController',
                                'introGame.songsService',
                                'introGame.artistService',
                                'introGame.currentSongService',
                                'introGame.gameLogicService',
                                'introGame.playLogService',
                                'introGame.songFactory',
                                'introGame.playFactory',
                                'introGame.albumFactory',
                                'introGame.albumFetcherService']);
